# Setup
title:        조사장(ChoSaJang) Blog
tagline:      조사장이 운영하는 github 개발 블로그입니다
baseurl:      ""
paginate:     1
locale:       "ko"

# About/contact
author:
  name:       ChoSaJang
  url:        http://chosajang.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
